name: Publish Nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd helper-dates && dotnet restore
    - name: Build
      run: cd helper-dates && dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test
    - name: Nuget Push
      run: cd helper-dates\bin\Release && dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.JWPRO_NUGET_KEY }}
